### ISSUE TITLE
Getting save status from main thread

### ISSUE THREAD

**Issue by yosun** [Chman/Moments#14]
Is it possible to get the save status callback from the main thread (for updating UI, enabling game objects etc)

**Comment by Chman** [comment]
See [this demo](https://github.com/Chman/Moments/blob/master/Moments%20Recorder/Demo/Scripts/Record.cs#L26) source file. Look for `OnPreProcessingDone`, `OnFileSaveProgress` and `OnFileSaved`. It's been a while since I've dug into Moments source code so I don't remember if it's totally thread safe... Worth a try though.
