### ISSUE TITLE
Including UI in recordings? 

### ISSUE THREAD

**Issue by yosun** [Chman/Moments#15]
It seems that the UI is not recorded in the gif? Is there a way to record the UI?

**Comment by Chman** [comment]
That's probably because your canvas render mode is set to Screen Space Overlay, so it's drawn after the camera has finished rendering. Change it to Screen Space Camera or World Space to have it appear in gifs.

If you're talking about the old IMGUI, then it's drawn after the camera no matter what so it can't be baked into the gif.
