### ISSUE TITLE
low color quality

### ISSUE THREAD

**Issue by cryax** [Chman/Moments#2]
The gif's color seems like in 16-bit format. Is there any way to improve color's quality?

**Comment by labsofawesome** [comment]
Do you have a sample of the gif and source image?

**Comment by Chman** [comment]
The Gif format is limited to 256-colors per palette. To make sure the colors are as good as possible, Moments creates Gif files with one palette per frame instead of one palette for the whole animation. There's isn't much more I can do to make it look better unfortunately, as it's a limitation of the Gif format.

**Comment by cryax** [comment]
thank you.
